spring:
  application:
    name: pigeon
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PigeonSkyRace
      # Uncomment and set these if MongoDB requires authentication
      # username: your_username
      # password: your_password
  server:
        port: 8081